name: Deploy
on:
  push:
    branches:
    - master
jobs:
  deploy_maps:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.PRIVATE_GITHUB_ACCESS_TOKEN }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            "https://api.github.com/repos/graphhopper/architecture/dispatches" \
            -d '{"event_type": "deploy", "client_payload": {}}'
